DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS studio;


CREATE TABLE studio (
	id SERIAL PRIMARY KEY,
	name VARCHAR (100) NOT NULL
);

CREATE TABLE games (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	year INT NOT NULL,
	studio_id INT NOT NULL, 
    FOREIGN KEY (studio_id) REFERENCES studio(id) ON DELETE CASCADE
);